#!/bin/sh

set -e

tag=${1:-42.0.0}

export TEST="true"
bundle exec rake "release:tag[$tag]" > log/release.log

# grep red lines (fatal errors)
if grep '\\[31m' log/release.log; then
    echo ""
    echo "Failure detected"
    exit 1
fi
